### ISSUE TITLE
Operator needs service account csi-rbd-nodeplugin-sa but rolebindings includes as ceph-csi-operator-csi-rbd-nodeplugin-sa

### ISSUE THREAD

**Issue by parth-gr** [ceph/ceph-csi-operator#106]
# Describe the bug #

currently, the operator code needs service account `csi-rbd-nodeplugin-sa` sa but rolebindings include as `ceph-csi-operator-csi-rbd-nodeplugin-sa`,

So either we need, 

1) Change the service account to add prefix `ceph-csi-operator`

2) Remove prefix `ceph-csi-operator` from the roles and rolebindings and clusterrolebindings.

Need a discussion on what change we should pick, and collect different views.

# Environment details #

- Image/version of ceph-csi-operator :
- Image/version of Ceph-CSI driver :
- Kubernetes cluster version :
- Ceph cluster version :

# Steps to reproduce #

1. Setup details: '...'
1. Deployment to trigger the issue '....'
1. See error

# Actual results #

Describe what happened

# Expected behavior #

# Logs #

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by travisn** [comment]
The service account names as defined currently, for example [csi-cephfs-ctrlplugin-sa](https://github.com/ceph/ceph-csi-operator/blob/main/config/rbac/csi_cephfs_ctrlplugin_service_account.yaml#L4), are nice and simple. Can we keep the simple names as the default? Why would we need a `ceph-csi-operator` prefix on the name? This would make a name of `ceph-csi-operator-csi-cephfs-ctrlplugin-sa` which seems unnecessarily long and redundant as the default. 

If someone wants to include a second driver in the namespace, they could set their own service account name and configure the [serviceAccountName](https://github.com/ceph/ceph-csi-operator/blob/main/api/v1alpha1/driver_types.go#L97-L99) to use an alternate. Isn't that the purpose of that field already to allow setting a non-default option? So we can keep the default option without the prefix. Let's optimize for the common case of one driver in the namespace.

**Comment by Madhu-1** [comment]
@travisn This is because of the way how we are installing, if we install using the kustomize this is expected.

**Comment by Madhu-1** [comment]
@parth-gr note we do have the option to specify the service account names for both the controller plugin and node-plugin in the Driver CR and the OperatorConfig CR which you can use.

**Comment by Madhu-1** [comment]
Reopening as now its not fixed but a way was provided to generate the CSI RBAC with expected names but we still need to fix the prefix part for the operator

**Comment by Madhu-1** [comment]
Closing this one as its fixed now.
