### ISSUE TITLE
omap side car is not deployed by default

### ISSUE THREAD

**Issue by rewantsoni** [ceph/ceph-csi-operator#131]
The driver API states that omap generator is [deployed by default](https://github.com/ceph/ceph-csi-operator/blob/5b68cb1ec8e3a03a0c441d74f82016a37a532016/internal/controller/driver_controller.go#L804) and we need to disable it explicitly but upon deployment, the csi-omap sidecar is not deployed.

Deployment check for [omap generator](https://github.com/ceph/ceph-csi-operator/blob/5b68cb1ec8e3a03a0c441d74f82016a37a532016/internal/controller/driver_controller.go#L804)

**Comment by Madhu-1** [comment]
@rewantsoni did you check it in the cluster, it will be deployed only if the GenerateOMapInfo is set to true in the CR

**Comment by rewantsoni** [comment]
@Madhu-1 Yes it is deployed when it's set to true. If that is the expected behavior, we should update the description [here]([deployed by default](https://github.com/ceph/ceph-csi-operator/blob/5b68cb1ec8e3a03a0c441d74f82016a37a532016/internal/controller/driver_controller.go#L804)) and in the doc as well

**Comment by Madhu-1** [comment]
yes it the expected behaviour, feel free to send a PR if any updates required in the docs
