### ISSUE TITLE
redundant option for providing encryption option?

### ISSUE THREAD

**Issue by iPraveenParihar** [ceph/ceph-csi-operator#143]
# Describe the bug #

I see there are two places where I can provide the KMS configMap name.
- `operatorconfig.spec.driverSpecDefaults.encryption`
- `drivers.spec.encryption`

However, operator only considers `drivers.spec.encryption` 
https://github.com/ceph/ceph-csi-operator/blob/f3030b0ac9f4915e6e09de5b60bfcfb95a380287/internal/controller/driver_controller.go#L1060-L1063

could we just remove the `operatorconfig.spec.driverSpecDefaults.encryption` field if not needed?

**Comment by leelavg** [comment]
It's by design, can refer https://github.com/ceph/ceph-csi-operator/blob/main/docs/design/operator.md

Option on driver overrides/merge corresponding value at operatorconfig

**Comment by Madhu-1** [comment]
This is as per the design to provide flexibility to override the encryption configuration at the driver level.

**Comment by iPraveenParihar** [comment]
Oops, I missed that in the code. Thanks for pointing it out!
Closing this issue.

**Comment by iPraveenParihar** [comment]
Hey, there is some other issue with setting up encryption, will raise other issue
