### ISSUE TITLE
Add github action for CI

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi-operator#149]
Add Github actions for the below operations

- [ ] GitHub Auto to auto assign a PR
- [ ] GitHub action for dependency-review
- [ ] GitHub action for mod check
- [ ] GitHub action for stale PR/issues

**Comment by Madhu-1** [comment]
Please feel freet o add more if anything extra actions are required.

**Comment by obnoxxx** [comment]
@Madhu-1  wrote:
> Add Github actions for the below operations
> 
>     * [ ]  GitHub Auto to auto assign a PR

do you mean reacting to an `/assign` comment in an issue?


>     * [ ]  GitHub action for dependency-review

could you elaborate what this action should do?


>     * [ ]  GitHub action for mod check
> 
>     * [ ]  GitHub action for stale PR/issues

**Comment by Madhu-1** [comment]
>do you mean reacting to an /assign comment in an issue?

Yes that's correct

> GitHub action for dependency-review

https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review is a document link about the dependency-review one.
