### ISSUE TITLE
Automatically add ms_mode=secure kernel mount Options when cluster encryption is enabled

### ISSUE THREAD

**Issue by parth-gr** [ceph/ceph-csi-operator#152]
# Describe the feature you'd like to have #

Automatically add ms_mode=secure kernel mount Options when cluster encryption is enabled in various cases such as upgrades and changes in network encryption status.
Replica of https://github.com/rook/rook/issues/13227

What new functionality do you want?

# Who is the end user and what is the use case where this feature will be valuable?
  
Who is going to use this feature and under what circumstances?

# How will we know we have a good solution? (acceptance criteria) #

Add a list of criteria that should be met for this feature to be useful

# Additional context #

**Comment by Madhu-1** [comment]
ceph-csi-operator cannot do it because the encryption is something configured on the ceph cluster based on the user provider options, the one who is using it needs to configure it ,in this case it rook/ocs-client-operator

**Comment by nb-ohad** [comment]
+1 to @Madhu-1 answer.
Ceph CSI operator already provide the needed nobs to allow the user (which can be an operator as well) to enable this setting
