### ISSUE TITLE
RFE: Add a new Xready field to the CR status to indicates its ready for consumption.

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi-operator#2]
I usually see phase/message/reason in resource Conditions, but it seems to me that Conditions have been going out of vogue. I think this is probable because they are incredibly hard to deal with in code and user scripts compared to having typed fields for status.

Many of the recent sig-storage KEPs use a `someResourceReady: bool` (e.g., `bucketReady: bool`, `snapshotReady: bool`) as well, so that users can know with a boolean whether their resource is ready.

Personally, I don't have a preference between `message` and `reason`. Both are alphabetically close to `phase` which should mean users see the outputs near each other as status items are added.

But I would suggest some sort of `xReady` bool that indicates when config is ready.

_Originally posted by @BlaineEXE in https://github.com/ceph/ceph-csi-operator/pull/1#discussion_r1608513625_

**Comment by nb-ohad** [comment]
@Madhu-1 We need to reopen the discussion about the status section on our CR. As the status section is user-facing, I think we need to do some research and thinking. Existing designs used in some of our other projects proved to create pain points, and I will object to a "copy-paste" approach without having a discussion first.
