### ISSUE TITLE
Readme should have contents

### ISSUE THREAD

**Issue by obnoxxx** [ceph/ceph-csi-operator#51]
# Describe the feature you'd like to have #

The Readme file currently does not have any content.

It should have a description of the project and how to use it.

# Who is the end user and what is the use case where this feature will be valuable?

developers and github users navigating to the project's page.

# How will we know we have a good solution? (acceptance criteria) #

Add a list of criteria that should be met for this feature to be useful

The Readme:
* is not empty
* describes what the project offers
* describes how to use the operator.

# Additional context #

**Comment by obnoxxx** [comment]
@Madhu-1 , @nb-ohad , @subhamkrai - FYI

**Comment by Madhu-1** [comment]
@obnoxxx sure, we will add this soon with more structuring format

**Comment by obnoxxx** [comment]
@Madhu-1  wrote: 
> @obnoxxx sure, we will add this soon with more structuring format

Thanks. but my main point was not lack of formatting, but lack of content: The Readme is empty.

**Comment by Madhu-1** [comment]
> @Madhu-1 wrote:
> 
> > @obnoxxx sure, we will add this soon with more structuring format
> 
> Thanks. but my main point was not lack of formatting, but lack of content: The Readme is empty.

Yes both are missing for now, will let it sooner
