### ISSUE TITLE
why a deepcopy here? afaik, `client.Get` fills in the memory that we supply and this is already a copy.

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi-operator#58]
why a deepcopy here? afaik, `client.Get` fills in the memory that we supply and this is already a copy.

_Originally posted by @leelavg in https://github.com/ceph/ceph-csi-operator/pull/24#discussion_r1675482809_

**Comment by nb-ohad** [comment]
To the best of my understanding, this is true only if your struct does not have pointers. In the case of a pointer, the pointer gets copied (which means the underlying value is shared). 
If we can prove that this is not the case and that Get creates a deep clone then we can remove our own deep clone operation

**Comment by leelavg** [comment]
Already looked at https://github.com/ceph/ceph-csi-operator/pull/24#discussion_r1687820974?

**Comment by Madhu-1** [comment]
@leelavg is this already sorted out and can be closed?

**Comment by leelavg** [comment]
Not solved.
