### ISSUE TITLE
Support topologybased provisioning

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi-operator#83]
cephcsi and Rook support topology-based provisioning https://github.com/search?q=repo%3Arook%2Frook%20EnableCSITopology&type=code we need to add the support for the same.

PS: will add more details later

**Comment by nb-ohad** [comment]
@Madhu-1 shouldn't we introduce code to detect it automatically instead of asking for user input?

**Comment by Madhu-1** [comment]
Still user need to provide labels to the csi driver, let's check this one Monday

**Comment by Madhu-1** [comment]
Fixed in https://github.com/ceph/ceph-csi-operator/pull/91
