### ISSUE TITLE
SnapshotPolicyType Const  value should match kubebuilder enum

### ISSUE THREAD

**Issue by subhamkrai** [ceph/ceph-csi-operator#95]
The defined `SnapshotPolicyType` is https://github.com/ceph/ceph-csi-operator/blob/4919ece1961894cca23a1bf13d80aff1bac58304/api/v1alpha1/driver_types.go#L72-L79 but kubebuilder enum has different rules with camelCase
https://github.com/ceph/ceph-csi-operator/blob/4919ece1961894cca23a1bf13d80aff1bac58304/api/v1alpha1/driver_types.go#L297-L298

**Comment by Madhu-1** [comment]
@subhamkrai do you have a plan to fix this?

**Comment by subhamkrai** [comment]
> @subhamkrai do you have a plan to fix this?

yes I will do
